/**
 * This file is auto-generated by the `import-svgs.mjs` script.
 */

export { default as Discord } from "./Discord.svg?react";
export { default as Farcaster } from "./Farcaster.svg?react";
export { default as Github } from "./Github.svg?react";
export { default as Mirror } from "./Mirror.svg?react";
export { default as Telegram } from "./Telegram.svg?react";
export { default as X } from "./X.svg?react";
