/**
 * This file is auto-generated by the `import-svgs.mjs` script.
 */

export { default as One } from "./One.svg?react";
export { default as Three } from "./Three.svg?react";
export { default as Two } from "./Two.svg?react";
